name: Staging Environment Build

on:
  create:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_mysql_password: ${{ secrets.MYSQL_PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      - name: Install aws-iam-authenticator
        run: |
          echo "Installing aws-iam-authenticator..."
          mkdir -p ~/aws
          AUTHENTICATOR_URL=$(curl -s https://api.github.com/repos/kubernetes-sigs/aws-iam-authenticator/releases/latest | grep "browser_download_url.*linux_amd64" | cut -d '"' -f 4)
          echo "Downloading from: $AUTHENTICATOR_URL"
          curl -L -o ~/aws/aws-iam-authenticator "$AUTHENTICATOR_URL"
          chmod +x ~/aws/aws-iam-authenticator
          sudo mv ~/aws/aws-iam-authenticator /usr/local/bin/
          echo "Installation completed successfully"

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.3

      - name: Terraform fmt
        run: terraform fmt

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Terraform Plan
        run: terraform plan -no-color

      - name: Terraform Apply
        run: terraform apply -no-color -auto-approve

      - name: Upload kubeconfig file
        uses: actions/upload-artifact@v4
        with:
          name: kubeconfig
          path: kubeconfig
